
services:

####################################################################################################
# app
####################################################################################################
  app:
    build:
      args:
        user: developer
        uid: 1001
      context: ./
      dockerfile: Dockerfile
    image: app
    container_name: loqui-app
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: loqui.test
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ~/.ssh:/root/.ssh
    depends_on:
      - db
      - redis
    networks:
      - loqui

####################################################################################################
# DATABASE (MySQL)
####################################################################################################
  db:
    image: mysql:8.0
    container_name: loqui-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql/data:/var/lib/mysql
      - ./docker-compose/mysql/logs:/var/log/mysql
      - ./docker-compose/mysql/ql:/docker-entrypoint-initdb.d
    networks:
      - loqui
####################################################################################################
# Nginx
####################################################################################################
  nginx:
    image: nginx:alpine
    container_name: loqui-nginx
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
      - ./docker-compose/nginx/ssl:/etc/nginx/conf.d/ssl
      - ./docker-compose/nginx/phpmyadmin.conf:/etc/nginx/conf.d/phpmyadmin.conf
    networks:
      - loqui

####################################################################################################
# phpMyAdmin
####################################################################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: loqui-phpmyadmin
    ports:
        - 8080:80
    links:
        - db
    restart: unless-stopped
    environment:
        PMA_HOST: db
        #PMA_USER: ${DB_USERNAME}
        #PMA_PASSWORD: ${DB_PASSWORD}
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
    networks:
        - loqui

 ####################################################################################################
# Redis
####################################################################################################
  redis:
    image: "redis:alpine"
    container_name: loqui-redis
    restart: unless-stopped
    volumes:
        - ./docker-compose/redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - loqui
####################################################################################################
# Typesense
####################################################################################################
  typesense:
    image: typesense/typesense:27.1
    restart: on-failure
    volumes:
      - ./docker-compose/typesense/data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
    ports:
            - '${FORWARD_TYPESENSE_PORT:-8108}:8108'
    environment:
        TYPESENSE_DATA_DIR: '${TYPESENSE_DATA_DIR:-/typesense-data}'
        TYPESENSE_API_KEY: '${TYPESENSE_API_KEY:-xyz}'
        TYPESENSE_ENABLE_CORS: '${TYPESENSE_ENABLE_CORS:-true}'
    networks:
        - loqui
    healthcheck:
        test:
            - CMD
            - wget
            - '--no-verbose'
            - '--spider'
            - 'http://localhost:8108/health'
        retries: 5
        timeout: 7s
networks:
  loqui:
    driver: bridge
