services:
  db:
    image: 'postgres:17'
    container_name: loqui_dev_postgres_container
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - loqui_dev_db:/var/lib/postgresql/data
    networks:
      - loqui
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s
  test-db:
    image: 'postgres:17'
    container_name: loqui_test_postgres_container
    ports:
      - '${FORWARD_DB_PORT:-5433}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - loqui_dev_db:/var/lib/postgresql/data
    networks:
      - loqui
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'loqui-redis:/data'
    networks:
      - loqui
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
  meilisearch:
    build:
      context: .
      # MODE=[dev | prod] docker compose up -d --build
      target: '--master-key ${MEILI_MASTER_KEY}'
    image: 'getmeili/meilisearch:latest'
    container_name: loqui_dev_meilisearch_container
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    environment:
      MEILI_MASTER_KEY: '${MEILI_MASTER_KEY}'
    volumes:
      - 'loqui-meilisearch:/meili_data'
    networks:
      - loqui
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--spider'
        - 'http://127.0.0.1:7700/health'
      retries: 3
      timeout: 5s
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    networks:
      - loqui
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: me@yanalshoubaki.com
      PGADMIN_DEFAULT_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
networks:
  loqui:
    driver: bridge
volumes:
  loqui_dev_db:
  loqui-redis:
  loqui-meilisearch:
  pgadmin-data:
