#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Checking for TypeScript errors..."
npm run lint
if [ $? -ne 0 ]; then
  echo "TypeScript errors found."
  npm run lint:fix
fi

echo "Running tests..."
composer test
if [ $? -ne 0 ]; then
  echo "Tests failed. Commit aborted."
  exit 1
fi

echo "Running Laravel Pint..."
composer pint
if [ $? -ne 0 ]; then
  echo "Laravel Pint failed."
  # add the changes to the commit
    git add .
    # commit the changes
    git commit --amend --no-edit
    # push the changes
fi
